baseurl = "/"
languageCode = "en-us"
title = "mananchong | 马南冲"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 2
[[menu.main]]
    name = "关于"
    url = "/cn/about/"
    weight = 3
[[menu.main]]
    name = "日志"
    url = "/cn/"
    weight = 4
[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Blog"
    url = "/en/"
    weight = 3
[[menu.en]]
    name = "Vitae"
    url = "/en/vitae/"
    weight = 4
[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 4
[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
[[menu.cn]]
    name = "简历"
    url = "/cn/vitae/"
    weight = 4
[[menu.cn]]
    name = "日志"
    url = "/cn/"
    weight = 3
[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 5
    

[params]
    description = "Personal website of Nanchong Ma; 马南冲的个人网站"
    footer = "&copy; [Nanchong Ma](/) 2004 - 2019"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
