baseurl = "/"
languageCode = "en-us"
title = "mananchong | 马南冲"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    cn = "/cn/:year/:month/:day/:slug/"
    en = "/en/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 2
[[menu.main]]
    name = "关于"
    url = "/cn/about/"
    weight = 3
[[menu.main]]
    name = "日志"
    url = "/cn/"
    weight = 4
[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Blog"
    url = "/en/"
    weight = 3
[[menu.en]]
    name = "Vitae"
    url = "/en/vitae/"
    weight = 4
[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 4
[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
[[menu.cn]]
    name = "简历"
    url = "/cn/vitae/"
    weight = 4
[[menu.cn]]
    name = "日志"
    url = "/cn/"
    weight = 3
[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 5
    

[params]
    description = "Personal website of Nanchong Ma; 马南冲的个人网站"
    footer = "&copy; [Nanchong Ma](/) 2004 - 2019"
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"
    customJS = [
        "js/fix-toc.js",
        "js/center-img.js",
        "js/right-quote.js",
        "js/no-highlight.js",
        "js/fix-footnote.js",
        "js/math-code.js",
        "js/external-link.js",
        "js/alt-title.js",
        "js/header-link.js"
    ]
[params.logo.en]
    img = "/images/logo.png"
    url = "/"
    alt = "Nanchong Ma"
    tag = ""

[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"

[params.author]
    en = "Nanchong Ma"
    cn = "马南冲"
